version: '3.8'
services:
  admin:
    image: kwonja/frontend-admin:latest
    container_name: admin
    ports:
      - "10002:3002" # 외부 포트 10002 -> 컨테이너 포트 3000
    environment:
      - NODE_ENV=production
  service:
    image: kwonja/frontend-service:latest
    container_name: service
    ports:
      - "10003:3003" # 외부 포트 10003 -> 컨테이너 포트 3003
    environment:
      - NODE_ENV=production
