version: "3"

services:
  admin:
    container_name: frontend_admin
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
    restart: always
    ports:
      - 3001:3001

  service:
    container_name: frontend_service
    build:
      context: .
      dockerfile: ./apps/service/Dockerfile
    restart: always
    ports:
      - 3002:3002

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname