version: "3.8"

services:
  admin:
    container_name: frontend_admin
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
    image: frontend_admin_image:latest
    restart: always
    ports:
      - "3001:3001"
    networks:
      - backend_network # 네트워크 연결

  service:
    container_name: frontend_service
    build:
      context: .
      dockerfile: ./apps/service/Dockerfile
    image: frontend_service_image:latest
    restart: always
    ports:
      - "3002:3002"
    networks:
      - backend_network # 네트워크 연결

networks:
  backend_network:
    driver: bridge # 기본 브리지 네트워크 사용
